# General Information
version: 1.0
released: 2014-06-03

# JWT Configuration
jwtConfig:
  privateKey: secretstring
  audience: http://ROOT-URL
  issuer: http://ROOT-URL
  expiryInMinutes: 20 # minutes